---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  interval: 1h
  values:
    fullnameOverride: victoria-logs
    retentionPeriod: 14d
    server:
      persistentVolume:
        enabled: true
        size: 2Gi
      route:
        enabled: true
        hostnames:
          - logs.example.com
        parentRefs:
          - name: traefik-gateway
            namespace: network
        extraRules:
          - filters:
              - type: RequestRedirect
                requestRedirect:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /select/vmui/
                  statusCode: 302
            matches:
              - path:
                  type: Exact
                  value: /
      serviceMonitor:
        enabled: true
    dashboards:
      enabled: true
