---
# yaml-language-server: $schema=https://schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
spec:
  targetNamespace: external-secrets
  path: ./kubernetes/main/apps/kube-system/external-secrets/stores
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
