---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superuser
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-local
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: postgres-superuser
    template:
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: devops/v1/system/cloudnative-pg/dev/login/connection
