---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    server:
      extraSecretEnvironmentVars:
        - envName: VAULT_TOKEN
          secretName: vault-unseal
          secretKey: VAULT_TOKEN
      dataStorage:
        enabled: true
        size: 2Gi
        # storageClass: "openebs-hostpath"
      ha:
        enabled: true
        replicas: 1
        raft:
          enabled: true
      ingress:
        enabled: true
        ingressClassName: "internal"
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: vault.homelab.arpa
    ui:
      enabled: true
  valuesFrom:
    - kind: ConfigMap
      name: vault-values
      valuesKey: values.yaml
