---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-apps-vpa
  namespace: flux-system
spec:
  path: ./infrastructure/base/monitoring/vpa
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: vpa
      namespace: monitoring
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 3m
