---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
  namespace: dbms
spec:
  interval: 1h
  chart:
    spec:
      chart: nats
      version: 2.12.2
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values: # https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml
    serviceMonitor:
      enabled: false
    config:
      jetstream:
        enabled: true
        pvc:
          enabled: true
          size: 1Gi
          # storageClassName: nfs-client
      cluster:
        enabled: true
