---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tempo
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: observability
  path: ./common/observability/tempo/app
  sourceRef:
    kind: GitRepository
    name: logging
    namespace: flux-system
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
