---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cockroachdb-operator
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v2.17.0
  url: https://github.com/cockroachdb/cockroach-operator
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/install
