---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v1.1.10
  url: http://github.com/dragonflydb/dragonfly-operator
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/helm/dragonfly-operator
