---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app infra-apps-cockroachdb-operator
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 15m
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cockroachdb-operator
  wait: true
  timeout: 5m
