---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://charts.fairwinds.com/stable
      chart: goldilocks
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 500m
          memory: 200Mi
    dashboard:
      replicaCount: 1
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 500m
          memory: 200Mi
