---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: dbms
spec:
  interval: 25m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.23.2
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  maxHistory: 2
  values: # https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/values.yaml
    monitoring:
      # -- Specifies whether the monitoring should be enabled. Requires Prometheus Operator CRDs.
      podMonitorEnabled: false
