---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: observability
spec:
  interval: 15m
  chart:
    spec:
      chart: gatus
      version: 1.4.4
      sourceRef:
        kind: HelmRepository
        name: gatus-chart
        namespace: flux-system
  values: # https://github.com/TwiN/helm-charts/blob/master/charts/gatus/values.yaml
    persistence:
      enabled: true
    deployment:
      strategy: RollingUpdate
      annotateConfigChecksum: true

    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

    ingress:
      enabled: false # HTTPRoute

    serviceMonitor:
      enabled: false

    config:
      maintenance:
        start: 07:58
        duration: 40m
        timezone: "Europe/Athens"
      metrics: true
      ui:
        title: Health Status
        header: Homelab Health Status
      connectivity:
        checker:
          target: 1.1.1.1:53
          interval: 1m
      default-endpoint: &defaults
        interval: "1m"
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 4000"
      endpoints:
        - name: "Internet"
          <<: *defaults
          url: "https://dev0ps.me"
          group: default
