---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
spec:
  interval: 10m
  chart:
    spec:
      chart: keda
      version: 2.18.1
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
# https://github.com/kedacore/charts/blob/main/keda/values.yaml
