---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app istio-base
spec:
  interval: 15m
  chart:
    spec:
      chart: base
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
# https://github.com/istio/istio/blob/be6c6d86a4ad41953c18e854748ba8916e849b11/manifests/charts/base/values.yaml
