# https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: &secret external-dns-secret
            key: api-token
    extraArgs:
      - --cloudflare-dns-records-per-page=1000
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-namespace=networking
      # - --gateway-name=traefik-gateway # https://kubernetes-sigs.github.io/external-dns/v0.19.0/docs/sources/gateway-api/#manifest-with-rbac
    triggerLoopOnEvent: true
    policy: sync
    sources: ["crd", "gateway-httproute"]
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters: ["default.com"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
