# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: mimir-distributed
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    usage_stats:
      enabled: false
    query_scheduler:
      replicas: 1
    querier:
      replicas: 1
    alertmanager:
      persistentVolume:
        enabled: true
      replicas: 1
    ingester:
      replicas: 1
      zoneAwareReplication:
        enabled: false
      persistentVolume:
        # storageClass: longhorn
        size: 5Gi
      resources:
        limits:
          memory: 1Gi
    store_gateway:
      zoneAwareReplication:
        enabled: false
      # persistentVolume:
        # storageClass: longhorn
    compactor:
      persistentVolume:
        # storageClass: longhorn
        size: 1Gi
    distributor:
      replicas: 1
