---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app echo
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./common/default/echo/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: logging
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
