apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-local
  namespace: external-secrets
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: token
          name: local-vault-token
          namespace: vault
      path: secrets
      server: http://10.89.89.11:8200
      version: v2
