---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - ${START_RANGE}-${END_RANGE}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: local-cluster
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
---
apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: ${METALLB_MEMBERLIST_SECRET}
type: Opaque
