---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api-crd
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.4.0
  ignore: |
    # exclude
    /*
    # include
    !config/crd/standard
