---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ntfy
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: observability
  path: ./common/observability/ntfy/app
  sourceRef:
    kind: GitRepository
    name: logging
    namespace: flux-system
  interval: 1h
  prune: true
  wait: false
